
---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
---

### PURPOSE:  create and then render a child Rmd file
```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = T   ) # easier to read
```

```{r library 		}
# print all labels
file <- knitr::current_input()
print(knitr::all_labels())
library(jimTools)
``` 

### Create fake chunk.Rmd
```{r}

# create_fake_rmd
#
create_fake_rmd  <- function() {
  writeLines(c("```{r fake_chunk}", 
               "x  <- 3", 
               "x", 
               "```"
               ), 
           here("rmd", "zzz_fake_chunk.Rmd")
           )
           
}
create_fake_rmd()
```


####  Now .... here is the child chunk
```{r test, child="zzz_fake_chunk.Rmd"}
```

#### Remove
```{r remove}
remove_fake_rmd  <- function(fake_file = 
                             here("rmd", "zzz_fake_chunk.Rmd")) 
{
    if (file.exists(fake_file)) file.remove( fake_file)

}
remove_fake_rmd()
```

```{r skeleton, eval=F, include=F}
file="/home/jim/.config/nvim/templates/skeleton.Rmd"
```

```{r render, eval=FALSE, include=FALSE 	} 
# TODO:  file is found when knitr runs (see above)

# file must be of form:
# dir/name_of_this_file    where dir is relative to project root

## In doubt?   USE  knitr and do not waste time!

## Want to embed Latex, stick to pdf output (html?   never sure!)

# NOTE:   .tex only works with PDF
# NOTE:    tex will NOT work with html
# NOTE:    md_document is considered HTML, and latex commands may fail.
# in general, pdf will look nicer


## GOOD PRACTICE:
#  Refer to files relative to project root, which should remain as working dir.
#  So why using `here` ?

{
file  <- "rmd/0200_basic_chunk_child.Rmd" 
file  <- basename(file)
file  <- here("rmd", file)
file
}


## Want github to display nicely rendered output?
##  *  include md_format
#   *  include output_dir = "out"
#   *  if .gitignore balks,  then add !out/**   to close .github

rmarkdown::render(file,
    #output_format = "pdf_document",
    output_format = "html_document")
    #output_format=c("html_document", "md_document"),
    #output_dir = "out",
    #output_file = "out")

# ==========================================
#  Example 1:  pdf| same name as source file | in wd |
# ==========================================

rmarkdown::render(file,
    output_format = "pdf_document")

# ============================================================
#  Example 2:  pdf | same name as source file | in pdf/|
# ============================================================
# pdf/  will be created

if (knitr::is_latex_output())  (
rmarkdown::render(file
    output_format = c("pdf_document") ,
    output_dir = "pdf")
)

if (knitr::is_html_output()) (

rmarkdown::render(file,
    output_format = c("html_document", "md_document"), 
    output_dir = "html")

)
```
