---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: lualatex  
    toc: true
    toc_depth:  4   
    keep_tex:  true
    keep_md:   true
  header-includes:  
    -  \usepackage{helvet}  
    -  \renewcommand{\familydefault}{\sfdefault}  
    -  \usepackage{ulem}
fontsize: 10pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  skeleton
---

\tableofcontents
```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      tidy = "styler",
                      error = TRUE,
                      collapse = T   ) # T easier to read

```



```{r, child= c('./slideA.Rmd', 'slideB.Rmd')}

```

\textcolor{red}{ color?}

<!-- reminder:   no code inside this chunk --> 
```{zsh, the_shell, child=c("slideC.sh")}
```



```{r render, eval=FALSE, include=FALSE 	} 
output_dir  <- Sys.getenv("OUTPUT_DIR")
output_dir

{
# get file
file <- "010_parent.Rmd"
file  <- normalizePath(file)
file

}

rmarkdown::render(file,
                   output_format = "beamer_presentation",
#                  output_format="html_document",
#                   output_format="pdf_document",
#                    intermediates_dir='./tmp',
#                    clean = F,              # leave tmp files
                    output_dir=output_dir
                  )
```

