---
title: "Play"
editor: visual
---

<div style="border: 2px solid green;"> in  a box </>

:::{style="color: red"}
## jim Rothstein
:::

### Clinical Trials Package Developer (R)

[jimrothstein\@gmail.com](jimrothstein@gmail.com)\
(831) 824-4304 (messages)

[linkedin: https://www.linkedin.com/in/jimrothstein](https://www.linkedin.com/in/jimrothstein){.uri}

<https:://www.linked.com/in/jimrothstein>

<https://github.com/jimrothstein>

### Seek R Developer Role with Clinical Trials data (ADaM, Admiral, pharmaverse)

### Overview

I am seeking developer role with Clinicial Trials. Have worked with Admiral and other Pharmaverse Packages.

### Technical Skills {#technical}

-   R, 4+ years package development, httr2, tidyverse/wrangle, data.table, shiny, quarto (some SCSS), webR, plots (base + ggplot2) roughly to level of Advanced R book.

-   SQL: 2+ years, joins, data.table, dplyr; mySQL

-   RStudio, Neovim/Nvim-R as IDE

-   Exposure to regression models, KNN, Random Forest, Logical Regression

-   R Shiny, modules, reactive programming, dashboard, bslib themes

-   Quarto, Rmarkdown, latex, pandoc, Katex, knitr, some SCSS, CSS

-   Git/Github: 3+ years, PR, merging

-   Zsh Shell: 3+ years scripts, regex, configuration

-   Lua - used to configure neovim, plugins including Nvim-R

-   OpenAPI: wrote R code to prepare code, requests and convert responses to tibbles, inlcuding outh2.

-   Linux (Debian, LinuxMint, Ubuntu): 4+ years, shell scripts, cron jobs, Rscripts

### Recent Projects & Skills {#recent}

-   (active) Fix issues in Pharamaverse Admiral and sdmtchecks R packages.

-   (active) Using Shiny developed preliminary dashboard for analysis of Drug Benefit Denials (public data from Center for Medicare and Medicaid (CMS)).

-   (active) Used youtube API and `httr` and `httr2` to add/modify youtube.com playlists. Used OAUTH tokens scope. Active participant developing book Web APIs with R, using openAPI framework.

-   Used tools in `rrapply` , `tidyr` , `vctrs`, `tibblify` to unravel deeply nested JSONs in tree/json format to table (from REST apis)

-   (active) Contribute to various Open Source projects (Github)

### RELATED WORK HISTORY:

2014 - present **R-Coders** Self-employed R programmer.

1996-2014 Self-employed contractor, including

-   Webmaster, community expatriate website in China, 2005 – 2008 Setup, maintain, promote expat community-based website in Dalian, China. Selected Joomla, hosting company, hired and trained student volunteers.

-   Capital IT Group, Dalian, China 2004- Mentor Chinese software engineers, light project management, pre and post sales.

-   Center for Electronic Art, San Francisco, 2002 Taught Java, mySQL, jsp classes. Also supervised graduate student modeling shipping/ ordering/ inventory system.

-   Teaching (1998-2012) Taught classes java, math, internet, statistics in China and California community college in US. Certified to teach math in at California community college.

Webmaster, Saratoga Systems, Campbell, CA (1996-1998) Maintain NT and IIS server. Various internet projects.

Web Database Development, Microsoft, Redmond, WA (1996) Web database applications using Asp, MS SQL; contractor.

Contract Programming Assignments: Chicago, IL (1986-1996) Designed and developed variety of business database applications (Paradox, Delphi, Access) For example

-   Developed relational database model for insurance company to track debt and assets of its multi-billion dollar joint ventures/commercial properties.\
-   Developed order tracking system (paradox).\
-   Contributed to bank risk management tool (ms access)

### Education {#education}

```         
BS MIT, physics
```

###  {#footer}

Jim Rothstein -- [jimrothstein\@gmail.com](jimrothstein@gmail.com) -- (831) 824-4304
