project:
  type: default
  title: misc
  output-dir: "."            ## NO indent, also _quarto.yml for entier project
  render:
    -  "*.qmd"

author: "jim"
#date: "12/20/2023"      # date started project
date: last-modified      # date started project
# pdf-engine: lualatex   # put this in pdf section, below
# bibliography: references.bib

#      - custom.scss
execute:
    error: true
    warning: true
    collapse: true
    standalone: true
    enabled: true    ##false: do not run chunks
    cache: false     ## knitr caches R chunks


format:
  typst:
    mainfont: "Liberation Serif"
    monofont: "Liberation Mono"
  html:
    html-math-method: katex
    code-fold: false
    toc: true
    toc_depth: 5
    toc_float: true
    number-sections: true
    number-depth: 3   #book feature only?
      #number-offset: 2
    #toc_location: body
    embed-resources: true # ie self-contained html
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    indent: false
    code-link: true             # hyperlink R functions
  pdf:
    pdf-engine: lualatex
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
