---
title: "100_html_CSS_examples.qmd"
format: 
  html:
    fontsize: 12px
    css: quarto_example_CSS.css
    html-math-method: katex
    toc:  true
editor: source 
editor_options: 
  chunk_output_type: console
---


***
### One 
<div class="intro">
Many ways to introduce css files in .qmd
<p>PURPOSE:    .qmd files, markdown, r code (knitr), CSS (via external CSS), embeded CSS in this page </p>
<p>USAGE1:     quarto preview <file.qmd>    renders and displays in browser </p>
USAGE2:      quarto render  <file.qmd>;   
        To view xdg-open <file.html>

_quarto.xml   controls output dir for *.html
</div>

***
### Two 

[An *aside* puts a note in right margin]{.aside}

***
### Three

$$\bar{y}$$  
$$\Reals$$

```{=html}
<h3>H3</h3>
```

***
### 3.

<a href="#">Hover example</a>

<a href="http://www.nytimes.com">Hover example</a>

***
### 3.2
The `echo: false` option disables the printing of code (only output is displayed).

We can use CSS or SASS to style individual words, or link
[phrases](https://google.com){style="font-size: 24px"} for spans (in-line), paragraphs
divs (see `selector`) or or formatting elements (e.g. header 2)

------------------------------------------------------------------------

[pink link to nytimes.com](https://nytimes.com){style="color:pink"}

using angle brackets: <https://nytimes.com>

[red text]{style="color:red"}

[background yellow]{style="background-color: yellow"}

[both red & background yellow]{style="color: red; background-color:yellow"}

***
3.3

::: {style="font-size: 8px; color:green"}
This paragrpah should be in very small font. ;aldkjf dsaf;ldsa fsa fdsa. lkajf sal;df as. adfljdf . adsflkjaf sa. a;lkdfj ad;f .
::: 

***
4

<!-- TODO: -->
<span class="blueish"> This `span` uses class from .css file, .blueish</span>

<p class="blueish">In CSS file `.blueish`  becomes `class="blueish"` in HTML</p>

***
5

<greenish>  This is "greenish" from external .css file </greenish>

***
6

:::
This paragrpah should be in very small font. ;aldkjf dsaf;ldsa fsa fdsa. lkajf sal;df as. adfljdf . adsflkjaf sa. a;lkdfj ad;f
:::

***
7

inline R: `r Sys.Date()`

***
8

### R chunk
```{r}
#| echo: false
#| 
print("second")
Sys.Date()
```
***
9

<h4> plain h4 </h4>

<h4 class=.special>h4 with class=.special </h4>

<h4 class=.test>h4 with class=.test </h4>

***
10

::: {.foo style="color: forestgreen; font-size: 32px"}

<!-- `:::` begins a Div -->
<example of div>
yukb goo

:::

***
    11

Here are some plain words that are not subject to any styling CSS or SCSS
    ***

<!-- Next:  apply a CSS style to a Span.  In this case the `special-words` -->

my [special-words]{style="color: goldenrod; font-size: 24px"}

***
12

### small header size two {style="color: red; font-size: 7px"}

### regular header size two

what else [can we do without]{style="color: darkorange; font-size: 12px"}going crazy
***
13

Also, be sure to render the document into an HTML so that you get the full effect.hope it helps. (edited)

<div style="border: 2px solid black;"> in  a box </>

<div class="text-box">This is some text inside a box.</div>

.text-box {
  border: 2px solid black; /* Creates a solid border */
  padding: 10px;          /* Adds space inside the box */
  margin: 20px;          /* Adds space outside the box */
  border-radius: 5px;    /* Rounds the corners of the box */
  background-color: #f9f9f9; /* Sets a background color */
}
