---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: lualatex  
    toc: true
    toc_depth:  4   
    keep_tex:  true
    keep_md:   true
  header-includes:  
    -  \usepackage{helvet}  
    -  \renewcommand{\familydefault}{\sfdefault}  
    -  \usepackage{ulem}
fontsize: 10pt   
geometry: margin=0.4in,top=0.25in   
TAGS:  skeleton
---
~/code/MASTER_INDEX.md



```
NO LUA engine in .Rmd

All LUA examples use  pandoc and lua filters.

render() will balk if put in a lua chunk, like zsh chunk.
```

PURPOSE:    Lua chunk inside .Rmd file
USAGE:      rmarkdown::render  as usual

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      tidy = "styler",
                      error = TRUE,
                      collapse = T   ) # T easier to read
```

#### supported engines (no lua!)
```{r}

names(knitr::knit_engines$get())
```



```{r render, eval=FALSE, include=FALSE 	} 
{
# get file
file <- "01_knitr_lua.Rmd"
file  <- normalizePath(file)
file


## Ref only
    # the_dir  <- dirname(file)
    # file  <- basename(file)
    # file  <- file.path(the_dir, file)

}

rmarkdown::render(file,
#                  output_format="html_document",
                    output_format="pdf_document")
```

