---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 4
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  4   
geometry: margin=0.4in,top=0.25in   
TAGS:  spin,
---
~/code/MASTER_INDEX.md

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = T   ) # T easier to read
```
```{r spin_test}
knitr::spin(hair = "2010_first_spin_code.R",
            knit = T,
            report = T)
            

```


```{r render, eval=FALSE, include=FALSE 	} 
output_dir  <- Sys.getenv("OUTPUT_DIR")
output_dir

{
file <- "/home/jim/code/publish_project/KNITR/2020_spin_master.Rmd"
file <- "2020_spin_master.Rmd"
file  <- here("KNITR", file)
file
}

rmarkdown::render(file,
                  output_format="html_document",
                  output_dir=output_dir
                  )


## replacement for here
if (F) {
  the_dir  <- dirname(file)
  file  <- file.path(the_dir, file)
}


```
